# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2 goop.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Hyperscrolling
source = ~/.config/hypr/hyprscrolling.conf

# Add any other personal Hyprland configuration below

# windowrule = workspace 5, class:qemu
env = XDG_MENU_PREFIX,arch-


# create virtual monitor expressly for streaming
#exec-once = hyprctl output create headless
# Set your TV's resolution here
#monitor = HEADLESS-1, 1920x1080@60, auto, 1


# mouse focus
input {
  follow_mouse = 2
  float_switch_override_focus = 0
  mouse_refocus = 1

}
cursor {
    no_warps = true
}
# galculator as object window
#windowrule = match:initial_class (org.speedcrunch.speedcrunch)$, float on, size 320 520, move 100%-w-20 100%-h-20
windowrule = match:initial_class (org.speedcrunch.speedcrunch)$, float on, size 320 520, move 1570 550

#windowrulev2 = float, class:^(org.speedcrunch.speedcrunch)$
#windowrulev2 = size 420 520, class:^(org.speedcrunch.speedcrunch)$
#windowrulev2 = move 100%-w-20 100%-h-20, class:^(org.speedcrunch.speedcrunch)$


# Start the infinite scrolling strip
# exec-once = /usr/bin/env bash /home/goopis/.local/bin/hypr-scroll-strip.sh &

# Keybinds to scroll left/right through all windows
# bind = SUPER, h, exec, pkill -USR1 -x hypr-scroll-strip.sh
# bind = SUPER, l, exec, pkill -USR2 -x hypr-scroll-strip.sh

# Odd workspaces → LEFT monitor
workspace = 1, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 9, monitor:eDP-1

# Even workspaces → RIGHT monitor
workspace = 2, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 6, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 10, monitor:DP-2

# Alt+Tab toggles to previously focused window
# bind = SUPER, q, focuscurrentorlast

# Alt+Shift+Tab toggles back
# bind = ALT SHIFT, TAB, focuscurrentorlast

